Output .github/assets/intro.gif

Set Shell "bash"
Set FontFamily "JetBrainsMono Nerd Font"
Set FontSize 19
Set Width 1160
Set Height 520
Set LineHeight 1.15
Set Theme { "name": "Kanagawa", "black": "#090618", "red": "#C34043", "green": "#76946A", "yellow": "#C0A36E", "blue": "#7E9CD8", "magenta": "#957FB8", "cyan": "#6A9589", "white": "#C8C093", "brightBlack": "#727169", "brightRed": "#E82424", "brightGreen": "#98BB6C", "brightYellow": "#E6C384", "brightBlue": "#7FB4CA", "brightMagenta": "#938AA9", "brightCyan": "#7AA89F", "brightWhite": "#DCD7BA", "background": "#1F1F28", "foreground": "#DCD7BA", "selection": "#2D4F67", "cursor": "#C8C093" }
Set Padding 25
Set Margin 20
Set MarginFill "#16161D"
Set BorderRadius 10
Set WindowBar Colorful
Set TypingSpeed 55ms
Set CursorBlink true
Set Framerate 24

Env LANG "en_US.UTF-8"

Hide
Type "export PS1='❯ '" Enter
Type "source .github/assets/intro.sh && clear" Enter
Show

Type "about" Enter
Sleep 3.5s

